Added Sub lists for both ordered and unordered
editor-js/list pull request #44
Opened 2020-08-08 02:09 UTC by ItechIndrustries

#43 #29 
- Commit
    - [91f1c6d](https://github.com/editor-js/list/commit/91f1c6da8ce297157f72e5576a2d82a29b55af72)

- Feature Preview

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/55910733/89700109-3b5cd100-d949-11ea-9e54-8153fe6c7465.gif)

2020-08-19 01:14 UTC, ItechIndrustries commented
Hey @PolinaShneider @neSpecc @talyguryn Some one please review this request

2020-08-19 06:04 UTC, talyguryn requested changes
You should not try to change package name from `@editorjs/list` to `@itech-indrustries/list` for this repo. 

Please, check code-style: spaces, blanks lines and line brakes. Change all `var` to `let` or `const`.

2020-08-19 06:04 UTC, talyguryn commented on src/index.js
> +    else{
Please, check code-style: spaces, blanks lines and line brakes.

2020-08-24 08:56 UTC, talyguryn requested changes

2020-08-24 08:56 UTC, talyguryn commented on src/index.js
> +      let dataEach = [];
```suggestion
      let dataEach = [];
      
```

2020-08-24 08:56 UTC, talyguryn commented on src/index.js
> +        }
```
} else if (value) {
```

2020-08-24 08:56 UTC, talyguryn commented on src/index.js
> +
```suggestion
```

2020-08-24 08:56 UTC, talyguryn commented on src/index.js
> +      if(typeof(item) == "object"){
```suggestion
      if (typeof(item) === "object") {
```

2020-08-24 08:56 UTC, talyguryn commented on src/index.js
> +      }else{
```suggestion
      } else {
```

2020-08-24 08:56 UTC, talyguryn commented on src/index.js
> +    return ulElem;
```suggestion

    return ulElem;
```

2020-08-24 08:56 UTC, talyguryn commented on src/index.js
> +
```suggestion
```

2020-08-24 08:56 UTC, talyguryn commented on src/index.js
> +    if (this.currentItem == this.currentItem.parentNode.childNodes[0]) {
```suggestion
    if (this.currentItem === this.currentItem.parentNode.childNodes[0]) {
```

2020-08-24 08:58 UTC, talyguryn commented
after pressing enter at the end of sublist there is a problem with margins for a new items in the main list

![image](https://user-images.githubusercontent.com/15259299/91024688-f9968080-e600-11ea-8889-d7d08b0e32e6.png)

2020-10-12 07:31 UTC, Froxz commented
#16

2020-11-03 14:12 UTC, Froxz commented
@talyguryn @PolinaShneider any chance this gets merged or requires more fixes?

2021-03-25 09:57 UTC, neSpecc commented
Resolved by making an advanced [Nested List](https://github.com/editor-js/nested-list) tool

2021-03-25 09:57 UTC, closed without merging